server.address=localhost
server.port=9091

spring.application.name=NotificationSender

spring.kafka.consumer.bootstrap-servers=localhost:9092

spring.mail.protocol=smtps
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=invite.me.notification@mail.ru
spring.mail.password=QST5y8oQREHldgrDuOEj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.mail.ru

mail.from.address=invite.me.notification@mail.ru
mail.from.name=InviteMe